version: '2'
services:
  shiny:
    build: .
    ports: 
      - "3838:3838"
    volumes:
      - ./logs:/var/log/shiny-server

  postgis:
    image: quay.io/codeformuenster/verkehrsunfaelle:2019-05-18
